version: '3.5'

name: kafka-native-zk
services:
  zookeeper:
    image: quay.io/ogunalp/zookeeper-native:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  broker1:
    image: quay.io/ogunalp/kafka-native:latest
    ports:
      - "9095:9092"
    environment:
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      SERVER_HOST: broker1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

  broker2:
    image: quay.io/ogunalp/kafka-native:latest
    ports:
      - "9096:9092"
    environment:
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      SERVER_HOST: broker2
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9096
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network
  broker3:
    image: quay.io/ogunalp/kafka-native:latest
    ports:
      - "9097:9092"
    environment:
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      SERVER_HOST: broker3
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9097
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafka-native-zk