---
name: Continuous Integration Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: |
          mvn -s .github/ci-maven-settings.xml -B \
            clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=${{ github.ref_name }}-${{ github.sha }}
      - name: Integration Tests with Maven
        run: |
          mvn -s .github/ci-maven-settings.xml -B \
            clean verify -Dtest-container -Dkafka-native-container-version=${{ github.ref_name }}-${{ github.sha }}
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: quay.io/ogunalp/kafka-native:${{ github.ref_name }}-${{ github.sha }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
